image::https://classroom.github.com/assets/open-in-vscode-2e0aaae1b6195c2367325f4f02e2d04e9abb55f0b24a779b69b11b9e10269abc.svg["Open in Visual Studio Code", link="https://classroom.github.com/online_ide?assignment_repo_id=16928608&assignment_repo_type=AssignmentRepo"]

= SAÉ 3.01 2024-2025

:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

Ce fichier `README.adoc`, permettra de présenter notre projet de SAE 3.01
Ainsi que les différents livrables et réalisations que nous avons effectués.

toc::[]

== Equipe et rôle

Projet est réalisé par::

- https://github.com/Cracotte-Mu-Da[GIARD--PELLAT Jules] : *Développeur*
- https://github.com/Romy514[CHAUVIERE Romy] *Scrum Master*
- https://github.com/AlbiMousse[ESTIENNE Alban-Moussa] *Product Owner*
- https://github.com/Quentin158[MARTINEZ Quentin] *Développeur*
- https://github.com/Matthias426[PAPA-PATSOUMOUDOU Matthias] *Développeur*

Tuteur/tutrice enseignant(e) de l'équipe:: 

- mailto:jean-michel.bruel@univ-tlse2.fr[Jean-Michel Bruel] +
- mailto:esther.pendaries@univ-tlse2.fr[Esther Pendaries] + 
- mailto:laurent.nonne@univ-tlse2.fr[Laurent Nonne] + 
- mailto:nabil.hanine@free.fr[Nabil Hanine] + 
- mailto:andre.peninou@univ-tlse2.fr[André Peninou] + 

== Sujet du projet

Ce projet consiste en la création d'un site e-commerce spécialisé dans la vente de produits magiques et mystiques, conçu pour offrir une expérience immersive aux amateurs de magie. Nommée "Abraca-dabra-cadabra," le site propose une large gamme de produits classés en diverses catégories, allant des baguettes magiques et potions aux grimoires, tenues, et ingrédients rares. L'objectif est de créer un environnement où les utilisateurs peuvent facilement naviguer entre les produits, bénéficier d'informations détaillées, et effectuer des achats en toute simplicité.

== Livrables

[cols="2,2,2",options=header]
|===
| Date    | Nom         |  Lien                       
| Sem.45  | Documentation conception      |  https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/blob/master/Documentations/Documentations_Conception/DocConception.adoc[Documentation Conception] 
|  | Collecte et analyse des données (IoT)      |   https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/tree/master/IoT[IoT]      
| Sem.46  | Ordre du jour #1      |  https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/blob/master/ODJ/ODJ%231.pdf[Ordre du jour #1]     
|  | Compte Rendu #1|   https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/blob/master/CR/CR%231.pdf[Compte Rendu #1]   
| Sem.47  | Ordre du jour #2      |  https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/blob/master/ODJ/ODJ%232.pdf[Ordre du jour #2]     
|  | Compte Rendu #2|   https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/blob/master/CR/CR%232.pdf[Compte Rendu #2]  
|  | IHM v0|   https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/tree/master/IHM[IHM v0] 
| Sem.48  | Ordre du jour #3      |     https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/blob/master/ODJ/ODJ%233.pdf[Ordre du jour #3] 
|  | Compte Rendu #3|  https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/blob/master/CR/CR%233.pdf[Compte Rendu #3] 
|  | IHM v1|  
|  | PHP v0|   https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/tree/009385c2517c71c242498bb6f847dc2bbbcaadfd/PHP[PHP v0]
|===

=== Evaluation communication EP

==== retour semaine 48

ODJ : Précisez qui est resp de chaque rubrique. CR : Manque synthese rdv client, manque analyse difficultés-réussites, manque resp prochaine réunion.
note : 1,9/3

== Réalisations 

Nous mettons à disposition plusieurs documents pour vous aider à comprendre à utiliser notre projet. Ces documents incluent :

=== 📘 Documentation de conception
Ce document est destiné aux développeurs et contributeurs techniques. Il décrit la conception du système et inclut des diagrammes UML détaillés ainsi que les cas d'utilisations principaux

- Lien : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/blob/master/Documentations/Documentations_Conception/DocConception.adoc[Documentation Conception]

=== 🛠️ Documentation technique
Ce document est destiné aux développeurs et contributeurs techniques. 
Il contient des informations détaillées sur l'architecture, le code, et les technologies utilisées dans ce projet.

- Lien : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/blob/master/Documentations/Documentation_Technique/DocTechniqueV0.adoc[Documentation Technique]

=== 🧑‍💻 Documentation utilisateur
Ce document s'adresse aux utilisateurs finaux. Il explique comment utiliser le projet et ses fonctionnalités.

- Lien : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/blob/master/Documentations/Documentation_Utilisateur/DocUtilisateurV0.adoc[Documentation Utilisateur]

=== ✅ Cahier de tests
Ce document détaille les cas de tests pour valider les fonctionnalités du projet en fonction des rôles définis (visiteur, client, administrateur). Chaque cas de test comprend les préconditions, les actions à réaliser et les résultats attendus.

- Lien : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/blob/master/Documentations/Cahier_Tests/CahierTestsV0.adoc[Cahier de tests]

== Gestion de projet & Qualité

Pour faciliter le suivi du projet, nous avons mis en place des outils de gestion disponibles sur GitHub:

=== 🚀 Release
La dernière version stable de l'application est disponible via le lien ci-dessous.
Téléchargez-la pour accéder aux dernières fonctionnalités

- Lien : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/releases/tag/v0.1.0[DevWeb v0.1.0]

=== 🗒️ Board GitHub
Notre board vous permettra de suivre l'état d'avancement des tâches. Il est organisé en trois colonnes :

- **A réaliser** : Liste des tâches à réaliser +
- **En cours** : Tâches en cours de réalisation + 
- **Terminé** : Tâches terminées +

- Lien : https://github.com/orgs/IUT-Blagnac/projects/261[Board]

=== 🎯 Milestones
Les milestones représentent chaque sprint du projet, accompagnés de leurs objectifs, délais ainsi que de leur avancement représenté en pourcentage.

- Lien : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/milestones[Milestones]

=== Evaluation bi-hebdomadaire

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=1704009585&format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=1704009585&format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=1704009585&format=interactive"></iframe>
++++
endif::[]

=== retour sprint 1 / Initialisation du dépôt
Il manque les rôles de chacun. Je ne trouve ni backlog de sprint, ni backlog produit !!  J'ai la doc de conception (qui ne précise pas le contexte du projet !) mais pas de liens vers les autres documentations qui devraient être initialisées ! Je n'ai pas de cahier de tests; pas de release ou de date de release !

=== Retour semaine 48

Backlog : j'ai des US mais pas de backlog produit avec evaluation de la complexité: il manque les finalités (afin de ) dans les US et critères acceptabilité. Backlog de sprint : ok milestone de sprint indiqué mais confus j'ai un projet mais on ne sait pas dans quel sprint on est !  Les US ne sont pas demandées en IOT. Tasks : Il faut les assigner et les rattacher à une US, je dois voir les tâches en cours de traitement dans le board du projet. Tests ok mais mettre à jour les résultats ! DOCS : coneption ok, pour user et tech à avancer on est à mi projet !! release ok 

=== Attendus
Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v0.1.2]
- Lien vers la doc technique
- Lien vers la doc utilisateur
- Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant
- Tests unitaires et plans de test
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application
