image::https://classroom.github.com/assets/open-in-vscode-2e0aaae1b6195c2367325f4f02e2d04e9abb55f0b24a779b69b11b9e10269abc.svg["Open in Visual Studio Code", link="https://classroom.github.com/online_ide?assignment_repo_id=16928608&assignment_repo_type=AssignmentRepo"]

= SAÉ 3.01 2024-2025

:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

Ce fichier `README.adoc`, permettra de présenter notre projet de SAE 3.01
Ainsi que les différents livrables et réalisations que nous avons effectués.

toc::[]

== Equipe

Projet est réalisé par::

- https://github.com/Cracotte-Mu-Da[GIARD--PELLAT Jules]
- https://github.com/Romy514[CHAUVIERE Romy]
- https://github.com/AlbiMousse[ESTIENNE Alban-Moussa]
- https://github.com/Quentin158[MARTINEZ Quentin]
- https://github.com/Matthias426[PAPA-PATSOUMOUDOU Matthias]

Tuteur/tutrice enseignant(e) de l'équipe:: 

mailto:jean-michel.bruel@univ-tlse2.fr[JMB]
mailto:esther.pendaries@univ-tlse2.fr[EP]

== Sujet du projet

Ce projet consiste en la création d'un site e-commerce spécialisé dans la vente de produits magiques et mystiques, conçu pour offrir une expérience immersive aux amateurs de magie. Nommé "Abraca-dabra-cadabra," le site propose une large gamme de produits classés en diverses catégories, allant des baguettes magiques et potions aux grimoires, tenues, et ingrédients rares. L'objectif est de créer un environnement où les utilisateurs peuvent facilement naviguer entre les produits, bénéficier d'informations détaillées, et effectuer des achats en toute simplicité.

== Livrables

[cols="2,2,2",options=header]
|===
| Date    | Nom         |  Lien                       
| Sem.45  | Documentation conception      |  https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/blob/master/Documentations/DocConception.adoc[Documentation Conception]     
|  | Collecte et analyse des données (IoT)      |   https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/tree/master/IoT[IoT]      
| Sem.46  | Ordre du jour #1      |  https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/blob/master/Documentations/ODJ%231.pdf[Ordre du jour #1]     
|  | Compte Rendu #1|   https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b10/blob/master/Documentations/CR%231.pdf[Compte Rendu #1]   
|===

== Réalisations 

TIP: Mettez ici toutes les informations nécessaire à l'utilisation de votre dépôt (comment on installe votre application, où sont les docs, etc.)

== Gestion de projet & Qualité

Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v0.1.2]
- Lien vers la doc technique
- Lien vers la doc utilisateur
- Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant
- Tests unitaires et plans de test
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application
